### ISSUE TITLE
ChromeDriver installer package is broken

### ISSUE THREAD

**Issue by NickGrantX** [ONSdigital/census-rm-acceptance-tests-2021#8]
The PyPi package `chromedriver_installer` has been broken since Google recently changed a webpage, which it was screen-scraping from, to find out the latest version. The PyPi package hasn't been maintained for 2 years and only has 1 contributor.

Consider using https://pypi.org/project/chromedriver-binary/ which is more-or-less a drop-in replacement and will save you the problems you're inevitably going to get... because we've had them in the SDC pipeline.

See: https://github.com/ONSdigital/rasrm-acceptance-tests/pull/261/files
Also: https://github.com/authomatic/chromedriver_installer/pull/10

**Comment by owencjones** [comment]
Appropriate binary can be `wget`'d or `cUrl`'d from the chromedriver website.

**Comment by AdamHawtin** [comment]
Fixed in https://github.com/ONSdigital/census-rm-acceptance-tests/pull/11.
